# Generated by Django 4.1.7 on 2023-05-07 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=128)),
                ('value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('reward', 'Reward'), ('debit', 'Debit')], max_length=7)),
                ('category', models.CharField(choices=[('salary', 'Salary'), ('bill', 'Bill'), ('leisure', 'Leisure'), ('shopping', 'Shopping'), ('vehicle', 'Vehicle')], max_length=8)),
            ],
        ),
    ]
