# Generated by Django 4.1.7 on 2023-03-19 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='type',
            field=models.CharField(choices=[('rewards', 'Rewards'), ('debit', 'Debit')], max_length=7),
        ),
    ]
