# Generated by Django 4.1.7 on 2023-03-19 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_alter_register_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='type',
            field=models.CharField(choices=[('reward', 'Reward'), ('debit', 'Debit')], max_length=7),
        ),
    ]
